services:
  api:
    command: uvicorn grosh_api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../services/api/src:/app/src:ro

  frontend:
    build:
      context: ../services/frontend
      target: dev
    volumes:
      - ../services/frontend/src:/app/src

  consumer:
    command: python -m watchfiles --filter python "python -m grosh_consumer.main" src/
    volumes:
      - ../services/consumer/src:/app/src

  ml:
    command: python -m watchfiles --filter python "python -m grosh_ml.main" src/
    volumes:
      - ../services/ml/src:/app/src

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    depends_on:
      - api
    networks:
      - grosh_net
